<a href="https://colab.research.google.com/github/ANURAG-SINGH17/Movie-Recommend-System/blob/main/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv(
    "TMDB1millonDataset.csv",
    engine="python",
    on_bad_lines="skip"
)

In [ ]:
df = df.dropna(subset=["backdrop_path"])

In [ ]:
df.shape

(6212, 29)

In [ ]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'tconst', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords', 'directors', 'writers', 'averageRating', 'numVotes',
       'cast'],
      dtype='object')

In [ ]:
df = df.dropna(subset=["title"])

In [ ]:
df.shape

(6212, 29)

In [ ]:
df.head(2)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,genres,production_companies,production_countries,spoken_languages,keywords,directors,writers,averageRating,numVotes,cast
0,27205,Inception,8.364,34495,Released,7/15/2010,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",Christopher Nolan,Christopher Nolan,8.8,2822861,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W..."
1,157336,Interstellar,8.417,32571,Released,11/5/2014,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan",8.7,2539628,"Matthew McConaughey, Anne Hathaway, Michael Ca..."

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6212 entries, 0 to 6212
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    6212 non-null   int64
 1   title                 6212 non-null   object
 2   vote_average          6212 non-null   float64
 3   vote_count            6212 non-null   int64
 4   status                6212 non-null   object
 5   release_date          6212 non-null   object
 6   revenue               6212 non-null   int64
 7   runtime               6212 non-null   int64
 8   adult                 6212 non-null   bool
 9   backdrop_path         6212 non-null   object
 10  budget                6212 non-null   int64
 11  homepage              2999 non-null   object
 12  tconst                6212 non-null   object
 13  original_language     6212 non-null   object
 14  original_title        6212 non-null   object
 15  overview              6212 non-null   object
 16  popularity            6212 non-null   float64
 17  poster_path           6212 non-null   object
 18  tagline               5499 non-null   object
 19  genres                6212 non-null   object
 20  production_companies  6204 non-null   object
 21  production_countries  6210 non-null   object
 22  spoken_languages      6209 non-null   object
 23  keywords              6105 non-null   object
 24  directors             6212 non-null   object
 25  writers               6196 non-null   object
 26  averageRating         6212 non-null   float64
 27  numVotes              6212 non-null   int64
 28  cast                  6203 non-null   object
dtypes: bool(1), float64(3), int64(6), object(19)
memory usage: 1.4+ MB

In [ ]:
df.isnull().sum()

id                         0
title                      0
vote_average               0
vote_count                 0
status                     0
release_date               0
revenue                    0
runtime                    0
adult                      0
backdrop_path              0
budget                     0
homepage                3213
tconst                     0
original_language          0
original_title             0
overview                   0
popularity                 0
poster_path                0
tagline                  713
genres                     0
production_companies       8
production_countries       2
spoken_languages           3
keywords                 107
directors                  0
writers                   16
averageRating              0
numVotes                   0
cast                       9
dtype: int64

In [ ]:
df = df.drop_duplicates().reset_index(drop=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# now select the column u want to use

In [ ]:
df_ML = df[[ 'id','title','overview','tagline', 'genres','keywords',]]

In [ ]:
df_ML.isnull().sum()

id            0
title         0
overview      0
tagline     713
genres        0
keywords    107
dtype: int64

In [ ]:
df_ML['tagline'] = df['tagline'].fillna('')
df_ML['keywords'] = df['keywords'].fillna('')
df_ML.isnull().sum()

id          0
title       0
overview    0
tagline     0
genres      0
keywords    0
dtype: int64

In [ ]:
df = df[[ 'id','title', 'vote_average','release_date',
       'adult', 'backdrop_path', 'original_title', 'overview',
       'popularity', 'poster_path']]

In [ ]:
df.isnull().sum()

id                0
title             0
vote_average      0
release_date      0
adult             0
backdrop_path     0
original_title    0
overview          0
popularity        0
poster_path       0
dtype: int64

In [ ]:
df_ML[['genres','tagline','overview']]

,genres,tagline,overview
0,"Action, Science Fiction, Adventure",Your mind is the scene of the crime.,"Cobb, a skilled thief who commits corporate es..."
1,"Adventure, Drama, Science Fiction",Mankind was born on Earth. It was never meant ...,The adventures of a group of explorers who mak...
2,"Drama, Action, Crime, Thriller",Welcome to a world without rules.,Batman raises the stakes in his war on crime. ...
3,"Action, Adventure, Fantasy, Science Fiction",Enter the world of Pandora.,"In the 22nd century, a paraplegic Marine is di..."
4,"Science Fiction, Action, Adventure",Some assembly required.,When an unexpected enemy emerges and threatens...
...,...,...,...
6207,Drama,The bonds we forge can change us forever.,"In seaside Italy, a Holocaust survivor with a ..."
6208,"Action, Crime, Drama, History, Thriller",,'Der Baader Meinhof Komplex' depicts the polit...
6209,"Thriller, Action, Crime",,A steely special ops agent finds his morality ...
6210,"Fantasy, Action, Thriller, Adventure",Unveiling millennium-old secrets.,As the deceased soul Ja-hong and his three aft...
6211,Drama,Once upon a time there was a dream that now ex...,"In a small suburb on the outskirts of Rome, th..."

In [ ]:
df_ML['tags'] = df_ML['overview']+ " " + df_ML['genres']+ " " + df_ML['tagline']

In [ ]:
df_ML.head()

,id,title,overview,tagline,genres,keywords,tags
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...",Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...","Cobb, a skilled thief who commits corporate es..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",The adventures of a group of explorers who mak...
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...",Batman raises the stakes in his war on crime. ...
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...","In the 22nd century, a paraplegic Marine is di..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,Some assembly required.,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",When an unexpected enemy emerges and threatens...

In [ ]:
df_ML.shape

(6212, 7)

NLP

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
def preprocess_text(text):
  # uppercase to lowercase
  text = str(text).lower()
  # remove the punctuation
  text = re.sub(r'[^a-zA-Z\s]','',text)
  # first perform tokenization then - remove stopWords
  words = text.split()
  words = [word for word in words if word not in stop_words]
  # lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [ ]:
df_ML['tags'] = df_ML['tags'].apply(preprocess_text)

In [ ]:
df_ML['tags'][0]

'cobb skilled thief commits corporate espionage infiltrating subconscious target offered chance regain old life payment task considered impossible inception implantation another person idea target subconscious action science fiction adventure mind scene crime'

In [ ]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Inception                                   0
Interstellar                                1
The Dark Knight                             2
Avatar                                      3
The Avengers                                4
                                         ...
The Life Ahead                           6207
The Baader Meinhof Complex               6208
AKA                                      6209
Along with the Gods: The Last 49 Days    6210
Bad Tales                                6211
Length: 6212, dtype: int64

In [ ]:
indices

           id                                  title
0       27205                              Inception
1      157336                           Interstellar
2         155                        The Dark Knight
3       19995                                 Avatar
4       24428                           The Avengers
...       ...                                    ...
6207   667869                         The Life Ahead
6208     6968             The Baader Meinhof Complex
6209  1102776                                    AKA
6210   518068  Along with the Gods: The Last 49 Days
6211   614292                              Bad Tales

[6212 rows x 2 columns]

In [ ]:
# Apply the Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1,2) , stop_words='english')

In [ ]:
tfidf_matrix = tfidf.fit_transform(df_ML['tags'])

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 236872 stored elements and shape (6212, 50000)>



Now we complete the matrix , tfidf , indecies
Now we will create are Machine Learning Model using Cosine similarity

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
def recommend(title, n = 10):
  if title not in  indices:
    return ['Movie not found']

  idx = indices[title]

  sim_score = cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [ ]:
recommend('The Dark Knight')

6079       Batman: The Long Halloween, Part One
25                        The Dark Knight Rises
879                              Batman Forever
6086                  In Order of Disappearance
4383                           Batman: Year One
2307                                        JFK
5367                 Batman: Gotham by Gaslight
3093    Batman: The Dark Knight Returns, Part 2
2540                   Batman: The Killing Joke
487                                      Batman
Name: title, dtype: object

In [ ]:
import pickle

In [ ]:
pickle.dump(tfidf_matrix , open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))